// This file is automatically generated. Do not modify it manually.

import { FirebaseOptions, initializeApp } from 'firebase/app';

const firebaseConfig: FirebaseOptions = {
  projectId: 'studio-4293394437-71df6',
  appId: '1:751244808020:web:1dd6c6de381eeb3eaec2c1',
  apiKey: 'AIzaSyCtlXgzORC8tPgTLgyQfmCr7VacyuyhmMQ',
  authDomain: 'studio-4293394437-71df6.firebaseapp.com',
  measurementId: '',
  messagingSenderId: '751244808020',
};

export const firebaseApp = initializeApp(firebaseConfig);
